INSERT INTO public.data103 (namethai,nameeng,info,infoeng,lat,log,timeopen,image) VALUES
	 ('ขนมดอกโดน','Kanom Dok Don','เป็นขนมที่มีรูปร่างน่าทาน รสชาติคล้ายขนมรังผึ้ง แต่ตัวแป้งบางและนุ่มกว่า และยังมีมะพร้าวให้ทานคู่กัน รสชาติหวานนุ่มละมุนลิ้น ','It''s an appetizing shape. It tastes like honeycomb candy. But the dough is thinner and softer. And there is also a coconut to eat together. The taste is sweet, soft and smooth.',0.0,0.0,'08:00 - 15:00 น','https://i.pinimg.com/736x/d4/db/4b/d4db4bee2c674581df6639c7f0151e6e.jpg'),
	 ('ขนมหัวเราะ','Laughing Candy','ย้อนวัยไปกับเมนูขนมหัวเราะหรือขนมหัวแตก ขนมไทยโบราณหากินยากโดยมีแป้งผสมกับไข่ไก่และเนย เติมกลิ่นวานิลลาปั้นเป็นก้อนกลมคลุกงาขาวแล้วกรีดเป็นรูปกากบาท เสร็จแล้วก็เอาไปทอดจนสุกถ้าได้ทานคู่กับกาแฟร้อนๆ ตอนเช้าจะอารมณ์ดีทั้งวัน','Go back in time with laughter desserts or cracked head desserts. An ancient Thai dessert that is hard to find with flour mixed with eggs and butter. Add vanilla scent, form a ball, mix with white sesame seeds and cut into a cross. After it''s done, take it to fry until it''s cooked if you eat it with hot coffee. The morning will be in a good mood all day.',13.7010671372435,100.502554550535,'08:00 - 15:00 น','https://th.bing.com/th/id/R.96aa5815d125c671f18fdeaaa2a853b0?rik=pbY9bVTNth8g%2fA&pid=ImgRaw&r=0'),
	 ('ข้าวยำปักษ์ใต้','Southern Rice Salad','เป็นอาหารท้องถิ่นทางภาคใต้ ข้าวยำเป็นอาหารที่มีคุณค่าทางอาหารสูง และเป็นสมุนไพรมีรสชาติ กลิ่น สีสันที่เป็นเอกลักษณ์ สะท้อนให้เห็นถึงวัฒนธรรมท้องถิ่นของภาคใต้','It is a local food in the south. Khao Yam is a food with high nutritional value. And is a herb with a unique taste, smell, color. reflecting the local culture of the south.',13.70089532,100.502872,'08:00 - 15:00 น','https://th.bing.com/th/id/OIP.O-hi1OXKJcjua17vaSl9TwHaE7?rs=1&pid=ImgDetMain'),
	 ('ข้าวแช่','Soaked Rice','ข้าวแช่คือ "ข้าวแช่น้ำเย็น" "ข้าว" แปลว่า ข้าว และ "แช" แปลว่า แช่ ในราวสมัยรัชกาลที่ 2 ได้ดัดแปลงสูตรอาหารมาจากอาหารมอญแล้วดัดแปลง ควรทำและบริโภคในฤดูร้อนตั้งแต่กลางเดือนมีนาคมถึงสิ้นเดือนเมษายน','Khao Chae is "Khao Chae Nam Yen". "Khao" means rice and "Chae" means soak. It should be made and consumed in the summer from mid-March to the end of April.',0.0,0.0,'08:00 - 15:00 น','https://th.bing.com/th/id/R.8682af92b05fd04080cf5eb9d816f064?rik=cx%2fJ45qYZLe1Qw&riu=http%3a%2f%2fbannuntawan.com%2fwp-content%2fuploads%2f2018%2f10%2f2016-%e0%b8%82%e0%b9%89%e0%b8%b2%e0%b8%a7%e0%b9%81%e0%b8%8a%e0%b9%88.jpg&ehk=2B2rfaZlp%2fa%2fRr4PwGtgxYbO7Vq17F6CtoJO2%2b%2ftat4%3d&risl=&pid=ImgRaw&r=0'),
	 ('ข้าวหมกบัสมาตี','Basmati Biryani','ถือเป็นอาหารของคนมุสลิมในประเทศไทย บัสมาติคือชื่อพันธุ์ข้าวของอินเดียเมล็ดเรียวยาวทานแล้วนุ่มหมดกับเครื่องเทศแขก เช่น อบเชย ลูกกระวาน กานพลู และ หญ้าฝรั่น เพื่อให้ข้าวมีสีเหลืองทองสวยและ มีกลิ่นหอม หรืออาจใช้ขมิ้นแท้แทนก็ได้','Considered as the food of Muslims in Thailand. Basmati is the name of a slender Indian rice variety. The grain is slender and soft. It is eaten with spices such as cinnamon, cardamom, cloves and saffron to give the rice a beautiful golden color and aroma. You can also use real turmeric instead.',13.7008928467551,100.502869362599,'08:00 - 15:00 น','https://img-global.cpcdn.com/recipes/ff3b63f1783df409/1200x630cq70/photo.jpg'),
	 ('ขนมปาก้า','Paka','ไม่มีข้อมูล','ไม่มีข้อมูล',0.0,0.0,'08:00 - 15:00 น','https://f.ptcdn.info/631/080/000/rusbj5pdm5sXVjqP73NI-o.jpg'),
	 ('ข้าวไก่แดง','Red Chicken Rice','ไม่มีข้อมูล','ไม่มีข้อมูล',0.0,0.0,'08:00 - 15:00 น','https://img.wongnai.com/p/1920x0/2022/02/12/d2bf3fee965d439981f36c45cd3a8954.jpg'),
	 ('ข้าวเหนียวดำหน้ากระฉีก','Shredded Black Glutinous Rice','ข้าวเหนียวดำมูนผสมกับข้าวเหนียวขาวให้เนื้อนุ่ม กินกับหน้ามะพร้าวทึนทึกที่เคี่ยวกับน้ำตาล เรียกว่ากระฉีก ได้อรรรถแบบขนมไทยแบบง่ายๆ','Black glutinous rice and white glutinous rice are mixed together to make the meat soft, eaten with coconut face and squeezed with sugar, which is called tearing. It is a follow-up model of simple Thai dessert.',0.0,0.0,'08:00 - 15:00 น','https://th.bing.com/th/id/OIP.efP_D2LMhMDxt9cEH8aFuwHaE-?w=247&h=180&c=7&r=0&o=5&pid=1.7'),
	 ('ขนมลูกชุบ','Luk Chub','ลูกชุบ เป็นขนมไทยชนิดหนึ่งทำด้วยถั่วเขียวบดกวนปั้นเป็นรูปร่างต่างๆระบายสี แล้วนำไปชุบวุ้นให้สวยงาม สีที่ใช้ทำลูกชุบนั้นนอกจากระบายลงบนถั่วเขียวกวนที่ปั้นแล้ว ยังใส่สีลงในถั่วกวนโดยตรงได้อีก','Luk Chub is a kind of Thai dessert made with mung bean paste, stirred and painted into various shapes. then plated with jelly to be beautiful The color used to make the plating balls is not only painted on the stir-fried mung bean. You can also add color directly to the bean paste.',13.70124254,100.5020135,'08:00 - 15:00 น','https://th.bing.com/th/id/R.c600ec43b0d4675aff92ea5e1b56d89e?rik=JlW2CCwPAGwrEQ&pid=ImgRaw&r=0'),
	 ('ยำทวาย','Yum Dawei','เป็นยำสูตรพื้นบ้านที่เรียนรู้มาจากทวายใช้ผักสดลวกหลากหลายชนิด ราดน้ำยำที่มีรสเปรี้ยวหวาน รสไม่จัดน้ำยำคล้ายน้ำจิ้มเนื้อสะเต๊ะ','It is a local recipe learned from Dawei using a variety of blanched fresh vegetables. Pour the spicy salad with sweet and sour taste. The flavor is not strong, the spicy sauce is similar to satay beef sauce.',0.0,0.0,'08:00 - 15:00 น','https://th.bing.com/th/id/R.45dcd88382ef2dbe2c5700998ebc891e?rik=9jBjyqs5tl6ulw&pid=ImgRaw&r=0');
INSERT INTO public.data103 (namethai,nameeng,info,infoeng,lat,log,timeopen,image) VALUES
	 ('รอยะ','Roya','ใช้อ่างดินเผาเหง้าหรือรากไม้ เป็นอุปกรณ์บดส่วนผสม ที่มีกระปิ พริกขี้หนูสวน น้ำตาล มะพร้าว มันกุ้ง เป็นเครื่องปรุงสำคัญนำมาคลุกเคล้ากับส่วนผสมมันเทศ มันแถว แตงกวา มะละกอ แครอท ลูกยอ','ไม่มีข้อมูล',0.0,0.0,'08:00 - 15:00 น','https://api.tourismthailand.org/upload/live/business_content_thumbnail/14139/P08002745.jpeg'),
	 ('สมองวัว','Cow Brain','ไม่มีข้อมูล','ไม่มีข้อมูล',13.70004116,100.50424,'08:00 - 15:00 น',''),
	 ('นาซิดาแก','Nasidagae','นาซิดาแก เป็นอาหารมลายูสามจังหวัดแท้ๆ เป็นอาหารที่ปรุงด้วยข้าวเจ้าผสมกับข้าวเหนียวและหางกะทินึ่งสุกคนให้ทั่ว และใส่ฮาลือบอ (เครื่องเทศ) แล้วคลุกเคล้าให้เข้ากัน รับประทานกับแกงปลาโอ แกงไก่ หรือแกงไข่ โรยหน้าด้วยข้าวคั่วและมะพร้าวคั่ว แนมด้วยพริกสด เป็นอาหารมื้อเช้าก็ได้ มื้อเที่ยงก็ได้ และยังเป็นอาหารสำคัญในพิธีต่างๆ','Nasi Dakae is authentic Malay food from three provinces. It is a dish cooked with rice mixed with glutinous rice and steamed coconut milk, stirring thoroughly. and add haluebo (spices) and mix well Serve with fish curry, chicken curry or egg curry, topped with roasted rice and roasted coconut. Naam with fresh chili It can be breakfast. Can have lunch and is also an important food in various ceremonies.',0.0,0.0,'08:00 - 15:00 น','https://th.bing.com/th/id/OIP.2PjSg6aKVTs8q7iz4fZeyAHaFj?rs=1&pid=ImgDetMain'),
	 ('ก๋วยเตี๋ยวแกง','Curry Noodles','ไม่มีข้อมูล','ไม่มีข้อมูล',13.6999846325704,100.504313399266,'08:00 - 15:00 น','https://th.bing.com/th/id/R.751b752c3797df73e1f948d067851675?rik=m7Xk2DJM0kYuCA&riu=http%3a%2f%2fwww.halalthailand.com%2fupfile%2f2017%2f10%2f01%2ffb%2ffb_150686105666.jpg&ehk=sD5gjoeeH21lS2Eu31t%2flThenpMfNB%2fqCkiHKVOlQaI%3d&risl=&pid=ImgRaw&r=0'),
	 ('ซูยี','Su Yi','เป็นขนมที่พี่น้องมุสลิมยินมทานในช่วงเดือนถือศีลอด และวันพิเศษต่างๆประกอบไปด้วยแป้งซูยีนมข้นหวาน นมข้นจืดและเครื่องเทศ','It is a snack that Muslim brothers and sisters eat during the fasting month. And special days consist of sugene flour, sweetened condensed milk. Condensed milk and spices.',13.70111928,100.5025546,'08:00 - 15:00 น','https://th.bing.com/th/id/R.4144ba8ae934b81485e2853434b74f44?rik=csXN0wgoK0vc3w&riu=http%3a%2f%2fwww.halalthailand.com%2fupfile%2f2017%2f11%2f17%2ffb%2ffb_151093596723.jpg&ehk=71vx21D6sxS%2btMWAPZiJm0LizfBC62g42I2V%2f0LadHk%3d&risl=&pid=ImgRaw&r=0'),
	 ('ไก่ทอด','Fried Chicken','ไก่ทอด เมนูยอดฮิตตลอดกาล เป็นเมนูไก่ทอดที่แตกต่างจากไก่ทอดทั่วไปคือ มีหอมเจียวที่เป็นจุดเด่นของร้านเป็นซิกเนเจอร์ที่มาถึงตลาดริมคลองเจริญกรุง 103 แล้วต้องได้ลองชิมไก่ทอดสูตรเด็ด','The fried chicken menu is always popular. It is a fried chicken menu that is different from ordinary fried chicken. It has a strong fragrance. This store is characterized by reaching 103 mature markets next to the canal and must taste delicious fried chicken recipes.',13.69985318,100.5044473,'08:00 - 15:00 น','https://images.deliveryhero.io/image/fd-th/LH/q5o2-hero.jpg'),
	 ('ขนมบูตู','Butu Cake','เป็นขนมพื้นบ้านโบราณของชาวมุสลิมที่มีเชื้อสายมาจากทางชาว อินโดนีเซียนิยมรับประทานตอนเช้าคู่กับชา กาแฟใช้แป้งสดที่ทำมาจากข้าว ผสมส่วนผสมพิเศษ','It is an ancient folk snack of Muslims who are descended from the people. Indonesia likes to eat in the morning with tea. Coffee uses fresh flour made from rice. mix special ingredients.',13.70128678,100.5021652,'08:00 - 15:00 น','https://img.wongnai.com/p/1920x0/2019/06/15/5e64afd79d4b479c9837e60fc7c1eee1.jpg'),
	 ('ขนมครกไข่','Khanom Krok Khai','นิยมกันทั่วทุกภาคของประเทศไทยเช่นภาคกลางภาคตะวันออกเฉียงเหนือภาคเหนือและส่วนใหญ่มักจะทำเป็นของฝาก ซึ่งเรียกกันว่าขนมไข่อบโบราณหรือขนมไข่โบราณสูตรต้นตำหรับ ภาคใต้นั้นก็เรียกว่าขนมไข่เช่นกันแต่คนส่วนใหญ่ภาคใต้นั้นนับถือศาสนาอิสลามร้อยละ ๘๐ และมีพื้นที่ติดชายแดนมาเลเซียซึ่งมีคนพูดภาษามลายูจึงทำให้บางพื้นที่เรียกขนมไข่ว่า “ขนมบูหลู”','It is popular in all regions of Thailand such as the central region, the northeastern region, the northern region, and most of them are often made as souvenirs. Which is called Khanom Khai Baked Ancient or Khanom Khai An ancient recipe. The southern part is also called khanom khai, but most people in the south are 80 percent Muslim and there are areas near the border with Malaysia, where people speak Malay, so some areas call khanom khan "Khanom Bulu".',13.69987894,100.5045056,'08:00 - 15:00 น','https://th.bing.com/th/id/OIP.mqgKX2AzABmXCSFJ56wnKAHaEK?rs=1&pid=ImgDetMain'),
	 ('ครองแครงกรอบ','Krong Kang','เป็นอาหารขึ้นชื่ออันดับ 2 ของที่นี่ เนื่องด้วยรูปลักษณ์ที่แปลกตา ทำมาจากแป้งที่เอามาทอด แล้วเอามาคลุกน้ำตาลและพริกไทย เป็นอาหารทานเล่นที่ดูจากภายนอกแล้วทานไปน่าจะเหนียว แต่ไม่เหนียวเลย เคี้ยวง่าย กรอบกำลังดี มีรสชาติหวาน มีความเผ็ดนิดๆ ทานได้เรื่อยๆ ','It is the second most famous food here due to its unusual appearance. Made from fried flour then mix with sugar and pepper It''s an appetizer that looks sticky from the outside. But not sticky at all, easy to chew, crispy, good taste, sweet and a little spicy. can eat continuously.',13.7010668961759,100.502566730751,'08:00 - 15:00 น','https://img.wongnai.com/p/400x0/2019/01/07/6191ecd170db4a6790811bf257e9f997.jpg'),
	 ('โรตีโรย','Rotiroy','มีต้นกำเนิดมาจากประเทศมาเลเซีย รูปร่างหน้าตาแปลกกว่าโรยทั่วไปเพราะใช้การโรยแป้งเป็นเส้นคล้ายการทำฝอยทองปกติจะทานในวันสำคัญสามารถทานเป็นของคาวหรือของหวานได้','Originated from Malaysia Its appearance is different from general sprinkling because it is used to sprinkle flour into a line similar to making Foi Thong. Usually eaten on important days, it can be eaten as a savory dish or dessert.',13.69968482,100.5047281,'08:00 - 15:00 น','https://th.bing.com/th/id/OIP.LZuJ7FxXuhaFXYgXg9BoYwAAAA?rs=1&pid=ImgDetMain');
INSERT INTO public.data103 (namethai,nameeng,info,infoeng,lat,log,timeopen,image) VALUES
	 ('แกงเนื้อมาซาล่า','Masala Beef Curry','แกงเนื้่อมาซาล่า ใครที่ชื่นชอบรสชาติเข้มข้นหอมนัวกลิ่นเครื่องเทศจัดจ้าน ต้องไม่พลาดเมนูนี้ ตัวแกงเข้มสะใจอย่างที่ว่า แถมเนื้อไก่นุ่มยุ่ยมาก ๆ จะกินกับข้าวสวยร้อน ๆ หรือแป้งนานก็ลงตัวแบบสุด ๆ ','Turmeric, Ma Sala, who likes the rich fragrance and the smell of spices, the restaurant must not miss this menu. The thick curry is so exciting, and the very soft chicken will be eaten with beautiful hot rice or long flour. It is the most perfect.',0.0,0.0,'08:00 - 15:00 น','https://th.bing.com/th/id/R.506dd3d9d4bd7b0c6fc9b14632586a37?rik=l26GG4X6t3taqA&riu=http%3a%2f%2fwww.bloggang.com%2fdata%2fb%2fbaanbaitong%2fpicture%2f1382950529.jpg&ehk=xT4DJXDykZoBwHhYId2o0mHuuctfi5FBbwVQSaNDkDY%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1'),
	 ('ร้านอาหารเทส 1','ไม่มีข้อมูล','ไม่มีข้อมูล','ไม่มีข้อมูล',0.0,0.0,'0.0',''),
	 ('ร้านอาหารเทส 2','ไม่มีข้อมูล','ไม่มีข้อมูล','ไม่มีข้อมูล',0.0,0.0,'0.0',NULL),
	 ('ร้านอาหารเทส 3','ไม่มีข้อมูล','ไม่มีข้อมูล','ไม่มีข้อมูล',0.0,0.0,'0.0',NULL),
	 ('ร้านอาหารเทส 4','ไม่มีข้อมูล','ไม่มีข้อมูล','ไม่มีข้อมูล',0.0,0.0,'0.0',NULL),
	 ('มะตะบะ','Mataba','แผ่นแป้งที่ใส่ไส้เนื้อสัตว์หรือผักต่าง ๆ ที่ปรุงรสสุกแล้ว ไส้มะตะบะเค็มมักจะมีการผสมเครื่องเทศเป็นหลัก เช่น ผงกะหรี่ กระชาย รากผักชี ที่นำมาโขลกรวมกัน แล้วนำลงกระทะ ผัดให้หอม ตามด้วยเนื้อสัตว์ที่สับละเอียด คั่วให้น้ำมันจากเนื้อออกมา เติมเครื่องปรุงรส เช่น เกลือ น้ำตาลทราย จากนั้นจึงนำผักต่าง ๆ ผัดให้เข้ากัน แล้วนำไปใส่ในแผ่นแป้ง ห่อให้มิด ทอดพอสุก หั่นเป็นชิ้น รับประทานกับเครื่องเคียงคืออาจาดแตงกวา มีส่วนผสมของแตงกวา หอมแดงซอย พริกขี้หนูหั่น น้ำส้มสายชู และน้ำตาลทราย','ไม่มีข้อมูล',13.6997988102447,100.504506923495,'08:00 - 15:00 น','https://s359.kapook.com/pagebuilder/1aaf403f-7e4c-423e-9d4e-e1f1a2fafeeb.jpg');
